[package]
name = "yomikomi"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.28"
num-traits = "0.2.17"
sentencepiece = "0.11.2"
serde_json = "1.0.108"
symphonia = { version = "0.5.3", features = ["all-codecs"] }
thiserror = "1.0.50"
zstd = "0.13.0"
